language: node_js
node_js:
  - 6.9
before_script: 
  - cd prototipo
  - "npm install"

#  - "0.6"
# services: mongodb
# default script - npm test
#env:
#  - CXX=g++-4.8
#before_install:
#- sudo apt-get update -qq
#- sudo apt-get install -qq [packages list]
