version: '2'

services:
  uchuva:
    build:
      ./prototipo
    restart: 
      always
    volumes:
        - /app
    ports:
      - "80:3000"
    environment:
      SHARE: /app
      CONDOR_URL: http://htcondor:8080/
      CONDOR_JOB_OWNER: uchuva
      BMANAGER: 3

  mongo:
    image: mongo
    expose:
      - "27017"
