output:
  logstash:
    enabled: true
    hosts:
      - 172.17.9.15:5044
    timeout: 15

filebeat:
  prospectors:
    -
      paths:
        - /app/logs/all-logs.log
      document_type: uchuva-log
